### PR TITLE
Support for EL2202 and EL1252

### PR DESCRIPTION
**Pull request by claudiolorini**
Hello,
if you are interested i've added the code for the following Beckhoff modules and i'd like to share it:
- EL2202: 2 channels fast digital out with tristate
- EL1252; 2 channels fast digital input with time-stamping capabilities

they have been tested with Machinekit, on a PC platform (Debian wheezy) with Linux 3.8-1, xenomai 2.6.3.

Ciao, C.

### CODE REVIEW

**Comment by sittner** [comment]
Thank you much. Could you tell me something about the state of the ECMS4 stuff? Is it also production ready or should we remove it from this PR?

**Comment by claudiolorini** [comment]
Hello Sascha,
i think for the moment i'ts better we stick to the commit related to EL2202 and EL1252 (if needed i can find the correct commit number).

The ECMS4 stuff (is a dual axis motor controller) is still heavily Work In Progress and i don't think it will be of general interest
because the board is not released on the market nor has been delivered to any research buddy of ours around the world...
Maybe in the future when the code is ready it could be useful as a reference for commercial dual axis drivers, in that case 
i'll do a PR for the ECMS4 stuff...

Ciao C.

________________________________________
Da: Sascha Ittner [notifications@github.com]
Inviato: venerd� 4 settembre 2015 15.35
A: sittner/linuxcnc-ethercat
Cc: Claudio Lorini
Oggetto: Re: [linuxcnc-ethercat] Support for EL2202 and EL1252 (#15)

Thank you much. Could you tell me something about the state of the ECMS4 stuff? Is it also production ready or should we remove it from this PR?

�

**Comment by sittner** [comment]
Please could you change/recreate the PR to include only the EL2202 and EL1252 stuff?

**Comment by claudiolorini** [comment]
...well not sure how to do it, but al least i can try! ;-)
i'll let you know when ready.
C.
________________________________________
Da: Sascha Ittner [notifications@github.com]
Inviato: venerd� 4 settembre 2015 16.04
A: sittner/linuxcnc-ethercat
Cc: Claudio Lorini
Oggetto: Re: [linuxcnc-ethercat] Support for EL2202 and EL1252 (#15)

Please could you change/recreate the PR to include only the EL2202 and EL1252 stuff?

�

**Pull request closed without merging**
